### ISSUE TITLE
square on the uniswap reserve

### ISSUE THREAD

**Issue by alexisgayte** [makerdao/univ2-lp-oracle#21]
Just looked at that,
There is a known vector attack on uniswap which is the liquidity removal. As there is no fees in v1 and not yet in v2,
Someone can add and remove all, then manipulate the reserve. While I don't believe there is a major issue on big pair, it can be on small pair.

I would check the deviation from your oracle and back fall to it if the gap is too big or reserves are diverging from the average.
or limiting the gap from your oracle let say +-10%.

https://github.com/makerdao/univ2-lp-oracle/blob/c500d2197f153f70da0e3005e74b87c37ee33a40/src/Univ2LpOracle.sol#L247

**Comment by alexisgayte** [comment]
Never mind as we stake them I guess it doesn't matter.

**Comment by alexisgayte** [comment]
I am reopening this one as I wanted to check, what the reason you guys don't use the average price facility offer by uniswap seems more adequate than the reserve?
`price0CumulativeLast`

**Comment by alexisgayte** [comment]
I am reopening this one, I am a bit confused with it to be honest.
As I read the comment there is an assumption that the k is constant, but it is not.

`require(balance0Adjusted.mul(balance1Adjusted) >= uint(_reserve0).mul(_reserve1).mul(1000**2), 'UniswapV2: K');`

the K is >=, it is not constant.

I guess everyone had a look at this one anyway.

**Comment by brianmcmichael** [comment]
Please read the notes. The uniswap provided price is not accurate.
