### ISSUE TITLE
is that ok to emit even if we don't change anything?

### ISSUE THREAD

**Issue by alexisgayte** [makerdao/univ2-lp-oracle#23]
https://github.com/makerdao/univ2-lp-oracle/blob/c500d2197f153f70da0e3005e74b87c37ee33a40/src/Univ2LpOracle.sol#L205

`link(3, address(0xxxxx))`

**Comment by brianmcmichael** [comment]
Yes. This is an authed function and we want to know about it even if it's successfully called in error.
